In [1]:
import numpy as np
import pickle

In [2]:
x_train = np.load('../ml/train_data/current_data/compressed_x_train2400.npy.npz')
x_train = x_train.f.arr_0
y_train = np.load('../ml/train_data/current_data/compressed_y_train2400.npy.npz')
y_train = y_train.f.arr_0

x_test = np.load('../ml/train_data/current_data/compressed_x_train1200.npy.npz')
x_test = x_test.f.arr_0
y_test = np.load('../ml/train_data/current_data/compressed_y_train1200.npy.npz')
y_test = y_test.f.arr_0

In [3]:
with open(f'../ml/train_data/current_data/x_train.pkl', 'rb') as f:
    x_train = np.concatenate([x_train, pickle.load(f)], axis=0)
with open(f'../ml/train_data/current_data/y_train.pkl', 'rb') as f:
    y_train = np.concatenate([y_train, pickle.load(f)], axis=0)

In [4]:
y_test

array([ 0.9025    ,  0.35848592, -0.54036009, ...,  0.34056163,
       -0.44012667,  0.48767498])

In [5]:
import lightgbm as lgb

train_data = lgb.Dataset(x_train, label=y_train)
 
# Create a LightGBM dataset for testing with features X_val and labels Y_val,
# and specify the reference dataset as train_data for consistent evaluation
test_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

In [6]:
params = {
    'objective': 'regression',
    'metric': 'mse',
    'learning_rate': 0.1
}
# 0.137879
num_round = 10000
bst = lgb.train(params, train_data, num_round, valid_sets=[
                test_data], early_stopping_rounds=50)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 2.798870 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53275
[LightGBM] [Info] Number of data points in the train set: 829018, number of used features: 220
[LightGBM] [Info] Start training from score 0.003504
[1]	valid_0's l2: 0.316607
Training until validation scores don't improve for 50 rounds
[2]	valid_0's l2: 0.303469
[3]	valid_0's l2: 0.292607
[4]	valid_0's l2: 0.283098
[5]	valid_0's l2: 0.275254
[6]	valid_0's l2: 0.268272
[7]	valid_0's l2: 0.262325
[8]	valid_0's l2: 0.257095
[9]	valid_0's l2: 0.25206
[10]	valid_0's l2: 0.247701
[11]	valid_0's l2: 0.244147
[12]	valid_0's l2: 0.24047
[13]	valid_0's l2: 0.237337
[14]	valid_0's l2: 0.234387
[15]	valid_0's l2: 0.231349
[16]	valid_0's l2: 0.228696
[17]	valid_0's l2: 0.226139
[18]	valid_0's l2: 0.223799
[19]	valid_0's l2: 0.221885
[20]	valid_0's l2: 0.219828
[21]	valid_0's l2: 0.217747
[22]	valid_0's

[275]	valid_0's l2: 0.145106
[276]	valid_0's l2: 0.145059
[277]	valid_0's l2: 0.145015
[278]	valid_0's l2: 0.144989
[279]	valid_0's l2: 0.144969
[280]	valid_0's l2: 0.144942
[281]	valid_0's l2: 0.144905
[282]	valid_0's l2: 0.144843
[283]	valid_0's l2: 0.144826
[284]	valid_0's l2: 0.144762
[285]	valid_0's l2: 0.144729
[286]	valid_0's l2: 0.144664
[287]	valid_0's l2: 0.144605
[288]	valid_0's l2: 0.144582
[289]	valid_0's l2: 0.144537
[290]	valid_0's l2: 0.144511
[291]	valid_0's l2: 0.144483
[292]	valid_0's l2: 0.144429
[293]	valid_0's l2: 0.144408
[294]	valid_0's l2: 0.144399
[295]	valid_0's l2: 0.144366
[296]	valid_0's l2: 0.144299
[297]	valid_0's l2: 0.144241
[298]	valid_0's l2: 0.144187
[299]	valid_0's l2: 0.14408
[300]	valid_0's l2: 0.144027
[301]	valid_0's l2: 0.143924
[302]	valid_0's l2: 0.143887
[303]	valid_0's l2: 0.143873
[304]	valid_0's l2: 0.143846
[305]	valid_0's l2: 0.143814
[306]	valid_0's l2: 0.143753
[307]	valid_0's l2: 0.143739
[308]	valid_0's l2: 0.143719
[309]	valid_0's

[559]	valid_0's l2: 0.139357
[560]	valid_0's l2: 0.139358
[561]	valid_0's l2: 0.139353
[562]	valid_0's l2: 0.139323
[563]	valid_0's l2: 0.139324
[564]	valid_0's l2: 0.139324
[565]	valid_0's l2: 0.139326
[566]	valid_0's l2: 0.139327
[567]	valid_0's l2: 0.139328
[568]	valid_0's l2: 0.13933
[569]	valid_0's l2: 0.139329
[570]	valid_0's l2: 0.139329
[571]	valid_0's l2: 0.139328
[572]	valid_0's l2: 0.139327
[573]	valid_0's l2: 0.139329
[574]	valid_0's l2: 0.139319
[575]	valid_0's l2: 0.139317
[576]	valid_0's l2: 0.139318
[577]	valid_0's l2: 0.139319
[578]	valid_0's l2: 0.139314
[579]	valid_0's l2: 0.139313
[580]	valid_0's l2: 0.139309
[581]	valid_0's l2: 0.139305
[582]	valid_0's l2: 0.139306
[583]	valid_0's l2: 0.139305
[584]	valid_0's l2: 0.139306
[585]	valid_0's l2: 0.139302
[586]	valid_0's l2: 0.139292
[587]	valid_0's l2: 0.139283
[588]	valid_0's l2: 0.139281
[589]	valid_0's l2: 0.139283
[590]	valid_0's l2: 0.139284
[591]	valid_0's l2: 0.139283
[592]	valid_0's l2: 0.139284
[593]	valid_0's

[843]	valid_0's l2: 0.138415
[844]	valid_0's l2: 0.138411
[845]	valid_0's l2: 0.138414
[846]	valid_0's l2: 0.138414
[847]	valid_0's l2: 0.138413
[848]	valid_0's l2: 0.138415
[849]	valid_0's l2: 0.138417
[850]	valid_0's l2: 0.138415
[851]	valid_0's l2: 0.138418
[852]	valid_0's l2: 0.138418
[853]	valid_0's l2: 0.13842
[854]	valid_0's l2: 0.138422
[855]	valid_0's l2: 0.138408
[856]	valid_0's l2: 0.138408
[857]	valid_0's l2: 0.13841
[858]	valid_0's l2: 0.138412
[859]	valid_0's l2: 0.13841
[860]	valid_0's l2: 0.138413
[861]	valid_0's l2: 0.138415
[862]	valid_0's l2: 0.138412
[863]	valid_0's l2: 0.138403
[864]	valid_0's l2: 0.138404
[865]	valid_0's l2: 0.138405
[866]	valid_0's l2: 0.138403
[867]	valid_0's l2: 0.138401
[868]	valid_0's l2: 0.138402
[869]	valid_0's l2: 0.138401
[870]	valid_0's l2: 0.1384
[871]	valid_0's l2: 0.1384
[872]	valid_0's l2: 0.138399
[873]	valid_0's l2: 0.138398
[874]	valid_0's l2: 0.138398
[875]	valid_0's l2: 0.138397
[876]	valid_0's l2: 0.138399
[877]	valid_0's l2: 0

[1123]	valid_0's l2: 0.138081
[1124]	valid_0's l2: 0.138081
[1125]	valid_0's l2: 0.138073
[1126]	valid_0's l2: 0.138074
[1127]	valid_0's l2: 0.138071
[1128]	valid_0's l2: 0.138065
[1129]	valid_0's l2: 0.138066
[1130]	valid_0's l2: 0.138058
[1131]	valid_0's l2: 0.138059
[1132]	valid_0's l2: 0.138057
[1133]	valid_0's l2: 0.138059
[1134]	valid_0's l2: 0.138049
[1135]	valid_0's l2: 0.13805
[1136]	valid_0's l2: 0.138043
[1137]	valid_0's l2: 0.138041
[1138]	valid_0's l2: 0.138039
[1139]	valid_0's l2: 0.138036
[1140]	valid_0's l2: 0.138036
[1141]	valid_0's l2: 0.138034
[1142]	valid_0's l2: 0.138034
[1143]	valid_0's l2: 0.138035
[1144]	valid_0's l2: 0.138034
[1145]	valid_0's l2: 0.138008
[1146]	valid_0's l2: 0.138009
[1147]	valid_0's l2: 0.138012
[1148]	valid_0's l2: 0.138012
[1149]	valid_0's l2: 0.138012
[1150]	valid_0's l2: 0.138013
[1151]	valid_0's l2: 0.138014
[1152]	valid_0's l2: 0.138011
[1153]	valid_0's l2: 0.138006
[1154]	valid_0's l2: 0.138007
[1155]	valid_0's l2: 0.138004
[1156]	vali

In [9]:
bst.predict(x_train[30:40])

array([-0.39816044,  0.58830509,  0.46333105,  0.17606777,  0.03048176,
        1.14641862, -0.4731624 , -0.85975167, -0.14875826, -0.29896855])

In [10]:
y_train[30:40]

array([-0.59873694,  0.56880009,  0.54036009,  0.26352009, -0.73509189,
        0.95      , -0.41812034, -0.857375  , -0.35848592,  0.56880009])

In [12]:
bst.save_model('model_0_137879.txt')

In [1]:
from fastai.tabular.all import *


In [22]:
x_train

array([[ 43.,  15.,  44., ...,  75.,  47.,  -1.],
       [ 23.,   0.,  20., ..., 226., 152.,   5.],
       [ 20.,   5.,  20., ...,  21., 102., 192.],
       ...,
       [ 17.,   0.,  23., ...,  77.,  61., 164.],
       [ 34.,  10.,  36., ...,  44., 179.,  15.],
       [ 24.,  23.,  25., ...,   5.,  94.,  -2.]])

In [23]:
y_train

array([ 0.46329123,  0.05656163, -0.63024941, ..., -0.22593554,
        0.59873694, -0.51334208])

In [9]:
from tsai.all import *

ModuleNotFoundError: No module named 'tsai'

In [47]:
df = pd.DataFrame(np.concatenate([np.concatenate([x_train, y_train.reshape(-1, 1)], axis=1), np.concatenate([x_test, y_test.reshape(-1, 1)], axis=1)], axis=0), cont_names=list(range(220)), y_names=220)

MemoryError: Unable to allocate 2.33 GiB for an array with shape (1413583, 221) and data type float64

In [ ]:
x_train.shape

In [30]:
to = TabularPandas(df)

In [31]:
dls = to.dataloaders(bs=64)

In [32]:
dls.show_batch()

In [33]:
learn = tabular_learner(dls)

In [34]:
learn.fit_one_cycle(1)

C:\Users\79672\AppData\Local\Programs\Python\Python36\envs\fastai\lib\site-packages\fastprogress\fastprogress.py:73: UserWarning: Your generator is empty.
  warn("Your generator is empty.")


In [36]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(learn.predict(pd.DataFrame(x_test)), y_train))

AttributeError: 'DataFrame' object has no attribute 'to_frame'

In [44]:
learn.predict(pd.Series(x_test[200]))

(    0     1     2    3    4    5    6    7    8    9    ...  211    212   213  \
 0  28.0  12.0  46.0  9.0  2.0  2.0  2.0  5.0  6.0  7.0  ... -1.0  103.0  68.0   
 
     214  215   216   217  218  219       220  
 0  25.0 -1.0  35.0  74.0  2.0 -1.0 -0.568707  
 
 [1 rows x 221 columns],
 tensor([-0.5687]),
 tensor([-0.5687]))

In [45]:
y_test[200]

-0.95

In [51]:
np.random.dirichlet([0.1], size=30)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])