In [1]:
import numpy as np
import pickle

In [2]:
x_train_1 = np.load('../ml/x_train4800.npz')
x_train_1 = x_train_1.f.arr_0
y_train_1 = np.load('../ml/y_train4800.npz')
y_train_1 = y_train_1.f.arr_0
"""
print(1)

x_train_2 = np.load('../ml/x_train7200.npz')
x_train_2 = x_train_2.f.arr_0
y_train_2 = np.load('../ml/y_train7200.npz')
y_train_2 = y_train_2.f.arr_0

print(2)

x_train_2 = np.load('../ml/x_train7200.npz')
x_train_2 = x_train_2.f.arr_0
y_train_2 = np.load('../ml/y_train7200.npz')
y_train_2 = y_train_2.f.arr_0

print(3)

x_train_3 = np.load('../ml/x_train9600.npz')
x_train_3 = x_train_3.f.arr_0
y_train_3 = np.load('../ml/y_train9600.npz')
y_train_3 = y_train_3.f.arr_0

print(4)

x_train_4 = np.load('../ml/x_train12000.npz')
x_train_4 = x_train_4.f.arr_0
y_train_4 = np.load('../ml/y_train12000.npz')
y_train_4 = y_train_4.f.arr_0

print(5)

x_train_5 = np.load('../ml/x_train14400.npz')
x_train_5 = x_train_5.f.arr_0
y_train_5 = np.load('../ml/y_train14400.npz')
y_train_5 = y_train_5.f.arr_0

print(6)

x_train_6 = np.load('../ml/x_train16800.npz')
x_train_6 = x_train_6.f.arr_0
y_train_6 = np.load('../ml/y_train16800.npz')
y_train_6 = y_train_6.f.arr_0
"""
print(7)


print(8)

x_test = np.load('../ml/x_train2400.npz')
x_test = x_test.f.arr_0
y_test = np.load('../ml/y_train2400.npz')
y_test = y_test.f.arr_0

1
2
3
4
7
8


In [3]:
#x_train = np.concatenate([x_train_1, x_train_2, x_train_3, x_train_4, x_train_5, x_train_6], axis=0)
x_train = np.concatenate([x_train_1, x_train_2, x_train_3, x_train_4], axis=0)

In [4]:
y_train = np.concatenate([y_train_1, y_train_2, y_train_3, y_train_4], axis=0)

In [ ]:
#y_test = (y_test > 0.0).astype(float)*2 - 1
#y_train = (y_train > 0.0).astype(float)*2 - 1
x_train.shape

In [14]:
x_test

array([[ 35.,   6.,  29., ...,  36., 129., 128.],
       [ 33.,  15.,  34., ...,  73., 127.,  35.],
       [ 33.,   0.,   1., ...,   2., 149.,  76.],
       ...,
       [ 24.,  13.,  28., ...,  -1.,   6., 138.],
       [ 11.,   6.,  43., ...,   8.,  -1.,  36.],
       [ 30.,  13.,  41., ...,  18.,  29., 154.]])

In [5]:
import lightgbm as lgb

train_data = lgb.Dataset(x_train, label=y_train)
 
# Create a LightGBM dataset for testing with features X_val and labels Y_val,
# and specify the reference dataset as train_data for consistent evaluation
test_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

In [ ]:
params = {
    'objective': 'regression',
    'metric': 'mse',
    'learning_rate': 0.2
}
# 0.14229
num_round = 10000
bst = lgb.train(params, train_data, num_round, valid_sets=[
                test_data], early_stopping_rounds=50)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 16.308574 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53283
[LightGBM] [Info] Number of data points in the train set: 4620774, number of used features: 220
[LightGBM] [Info] Start training from score 0.003165
[1]	valid_0's l2: 0.319716
Training until validation scores don't improve for 50 rounds
[2]	valid_0's l2: 0.305496
[3]	valid_0's l2: 0.293664
[4]	valid_0's l2: 0.283556
[5]	valid_0's l2: 0.275063
[6]	valid_0's l2: 0.267609
[7]	valid_0's l2: 0.261444
[8]	valid_0's l2: 0.256097
[9]	valid_0's l2: 0.251223
[10]	valid_0's l2: 0.246684
[11]	valid_0's l2: 0.242881
[12]	valid_0's l2: 0.239366
[13]	valid_0's l2: 0.235988
[14]	valid_0's l2: 0.233173
[15]	valid_0's l2: 0.230398
[16]	valid_0's l2: 0.227637
[17]	valid_0's l2: 0.225226
[18]	valid_0's l2: 0.222906
[19]	valid_0's l2: 0.220829
[20]	valid_0's l2: 0.218737
[21]	valid_0's l2: 0.21684
[22]	valid_

In [17]:
bst.predict(x_test[:10])

array([ 0.43930616, -0.22495369,  0.59613679, -1.20382113,  1.1814764 ,
       -0.63594428,  0.14447957, -0.16605443,  1.7059398 ,  0.2521981 ])

In [19]:
y_test[:10] / 2

array([ 0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5])

In [9]:
bst.save_model('new_critic.txt')