In [1]:
import numpy as np
import pickle

In [2]:
x_train = np.load('../ml/x_train600.npz')
x_train = x_train.f.arr_0
y_train = np.load('../ml/y_train600.npz')
y_train = y_train.f.arr_0

x_test = np.load('../ml/x_train50.npz')
x_test = x_test.f.arr_0
y_test = np.load('../ml/y_train50.npz')
y_test = y_test.f.arr_0

In [3]:
y_test

array([ 0.875     ,  0.75757576, -0.18181818, ..., -0.92      ,
       -0.46153846,  0.59259259])

In [4]:
x_test

array([[ 46.,   0.,  31., ...,  31.,  13.,  -1.],
       [ 24.,  16.,  25., ..., 152.,  64.,  -1.],
       [ 29.,  17.,  22., ...,  15., 100.,  43.],
       ...,
       [  1.,   0.,  23., ...,  -1.,  31.,  -1.],
       [ 14.,   0.,  30., ...,  62.,  19.,  22.],
       [  8.,   0.,  29., ...,  56.,  -1., 234.]])

In [5]:
import lightgbm as lgb

train_data = lgb.Dataset(x_train, label=y_train)
 
# Create a LightGBM dataset for testing with features X_val and labels Y_val,
# and specify the reference dataset as train_data for consistent evaluation
test_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

In [6]:
params = {
    'objective': 'regression',
    'metric': 'mse',
    'learning_rate': 0.1
}
# 0.14229
num_round = 10000
bst = lgb.train(params, train_data, num_round, valid_sets=[
                test_data], early_stopping_rounds=50)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.677836 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53253
[LightGBM] [Info] Number of data points in the train set: 291672, number of used features: 220
[LightGBM] [Info] Start training from score 0.004857
[1]	valid_0's l2: 0.312558
Training until validation scores don't improve for 50 rounds
[2]	valid_0's l2: 0.299364
[3]	valid_0's l2: 0.288294
[4]	valid_0's l2: 0.278842
[5]	valid_0's l2: 0.270833
[6]	valid_0's l2: 0.264023
[7]	valid_0's l2: 0.258333
[8]	valid_0's l2: 0.252803
[9]	valid_0's l2: 0.248164
[10]	valid_0's l2: 0.243939
[11]	valid_0's l2: 0.240042
[12]	valid_0's l2: 0.236284
[13]	valid_0's l2: 0.232946
[14]	valid_0's l2: 0.229876
[15]	valid_0's l2: 0.226905
[16]	valid_0's l2: 0.224154
[17]	valid_0's l2: 0.221733
[18]	valid_0's l2: 0.219133
[19]	valid_0's l2: 0.217003
[20]	valid_0's l2: 0.21511
[21]	valid_0's l2: 0.213283
[22]	valid_0'

[275]	valid_0's l2: 0.144546
[276]	valid_0's l2: 0.144509
[277]	valid_0's l2: 0.144508
[278]	valid_0's l2: 0.144501
[279]	valid_0's l2: 0.144483
[280]	valid_0's l2: 0.144464
[281]	valid_0's l2: 0.144461
[282]	valid_0's l2: 0.144429
[283]	valid_0's l2: 0.144421
[284]	valid_0's l2: 0.144394
[285]	valid_0's l2: 0.144386
[286]	valid_0's l2: 0.144398
[287]	valid_0's l2: 0.144372
[288]	valid_0's l2: 0.144358
[289]	valid_0's l2: 0.144335
[290]	valid_0's l2: 0.14434
[291]	valid_0's l2: 0.144308
[292]	valid_0's l2: 0.144303
[293]	valid_0's l2: 0.144269
[294]	valid_0's l2: 0.144234
[295]	valid_0's l2: 0.144185
[296]	valid_0's l2: 0.144132
[297]	valid_0's l2: 0.144126
[298]	valid_0's l2: 0.144141
[299]	valid_0's l2: 0.144103
[300]	valid_0's l2: 0.144112
[301]	valid_0's l2: 0.144101
[302]	valid_0's l2: 0.144088
[303]	valid_0's l2: 0.144062
[304]	valid_0's l2: 0.144061
[305]	valid_0's l2: 0.144011
[306]	valid_0's l2: 0.144001
[307]	valid_0's l2: 0.143963
[308]	valid_0's l2: 0.143967
[309]	valid_0's

[558]	valid_0's l2: 0.14229
[559]	valid_0's l2: 0.142296
[560]	valid_0's l2: 0.142302
[561]	valid_0's l2: 0.142313
[562]	valid_0's l2: 0.142316
[563]	valid_0's l2: 0.142328
[564]	valid_0's l2: 0.142336
[565]	valid_0's l2: 0.142346
[566]	valid_0's l2: 0.142365
[567]	valid_0's l2: 0.142367
[568]	valid_0's l2: 0.142349
[569]	valid_0's l2: 0.14234
[570]	valid_0's l2: 0.14234
[571]	valid_0's l2: 0.142338
[572]	valid_0's l2: 0.142344
[573]	valid_0's l2: 0.142327
[574]	valid_0's l2: 0.142324
[575]	valid_0's l2: 0.142323
[576]	valid_0's l2: 0.142311
[577]	valid_0's l2: 0.142317
[578]	valid_0's l2: 0.142331
[579]	valid_0's l2: 0.142337
[580]	valid_0's l2: 0.142341
[581]	valid_0's l2: 0.142344
[582]	valid_0's l2: 0.142351
[583]	valid_0's l2: 0.142363
[584]	valid_0's l2: 0.142385
[585]	valid_0's l2: 0.142412
[586]	valid_0's l2: 0.142419
[587]	valid_0's l2: 0.142422
[588]	valid_0's l2: 0.142439
[589]	valid_0's l2: 0.142435
[590]	valid_0's l2: 0.142425
[591]	valid_0's l2: 0.142422
[592]	valid_0's l

In [7]:
bst.predict(x_test[:10])

array([ 0.38226461,  0.55441122, -0.27336858,  0.9298043 , -1.17172399,
       -0.07586931, -0.01459862, -0.19446404, -0.15623005,  0.26219081])

In [8]:
y_test[:10]

array([ 0.875     ,  0.75757576, -0.18181818,  0.85      , -0.81081081,
        0.03225806, -0.89285714, -0.09090909,  0.32258065, -0.4       ])

In [9]:
bst.save_model('new_critic.txt')