In [12]:
import numpy as np
import pickle

In [4]:
x_train = np.load('../ml/compressed_x_train2400.npy.npz')
x_train = x_train.f.arr_0
y_train = np.load('../ml/compressed_y_train2400.npy.npz')
y_train = y_train.f.arr_0

x_test = np.load('../ml/compressed_x_train1200.npy.npz')
x_test = x_test.f.arr_0
y_test = np.load('../ml/compressed_y_train1200.npy.npz')
y_test = y_test.f.arr_0

In [13]:
with open(f'../ml/x_train.pkl', 'rb') as f:
    x_train = np.concatenate([x_train, pickle.load(f)], axis=0)
with open(f'../ml/y_train.pkl', 'rb') as f:
    y_train = np.concatenate([y_train, pickle.load(f)], axis=0)

In [36]:
y_test

array([ 0.9025    ,  0.35848592, -0.54036009, ...,  0.34056163,
       -0.44012667,  0.48767498])

array([0.73164562, 0.52828081, 0.1848753 , ..., 0.38703223, 0.79936847,
       0.24332896])

In [14]:
import lightgbm as lgb

train_data = lgb.Dataset(x_train, label=y_train)
 
# Create a LightGBM dataset for testing with features X_val and labels Y_val,
# and specify the reference dataset as train_data for consistent evaluation
test_data = lgb.Dataset(x_test, label=y_test, reference=train_data)

In [24]:
params = {
    'objective': 'binary',
    'metric': 'mse',
    'learning_rate': 0.1
}
#0.137879 (1265 итераций)
num_round = 10
bst = lgb.train(params, train_data, num_round, valid_sets=[
                test_data], early_stopping_rounds=50)

[LightGBM] [Info] Number of positive: 419073, number of negative: 409945
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 2.622498 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53275
[LightGBM] [Info] Number of data points in the train set: 829018, number of used features: 220
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.505505 -> initscore=0.022022
[LightGBM] [Info] Start training from score 0.022022
[1]	valid_0's l2: 0.574475
Training until validation scores don't improve for 50 rounds
[2]	valid_0's l2: 0.565455
[3]	valid_0's l2: 0.557469
[4]	valid_0's l2: 0.550582
[5]	valid_0's l2: 0.544564
[6]	valid_0's l2: 0.539142
[7]	valid_0's l2: 0.534299
[8]	valid_0's l2: 0.530074
[9]	valid_0's l2: 0.526172
[10]	valid_0's l2: 0.522627
Did not meet early stopping. Best iteration is:
[10]	valid_0's l2: 0.522627


In [35]:
bst.predict(x_train[30:40])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
y_train[30:40]

array([-0.59873694,  0.56880009,  0.54036009,  0.26352009, -0.73509189,
        0.95      , -0.41812034, -0.857375  , -0.35848592,  0.56880009])

In [20]:
from fastai.tabular.all import *

ModuleNotFoundError: No module named 'fastai'