In [34]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [35]:
import pickle

In [36]:
with open('train.pickle', 'rb') as f:
     (train_in, train_out) = pickle.load(f)

In [37]:
with open('test.pickle', 'rb') as f:
     (test_in, test_out) = pickle.load(f)

In [48]:
model_rf = RandomForestRegressor(n_jobs=-1, verbose=2, n_estimators=100, min_samples_split=100)

In [49]:
model_rf.fit(train_in, train_out)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.


building tree 1 of 100
building tree 2 of 100building tree 3 of 100

building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100


[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  4.3min


building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed: 12.2min finished


RandomForestRegressor(min_samples_split=100, n_jobs=-1, verbose=2)

In [50]:
model_rf.predict(test_in)[:100]

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.2s finished


array([-0.00866763, -0.16530198, -0.1561505 , -0.1815686 ,  0.01385284,
        0.0677373 ,  0.01636165,  0.20811139, -0.02931016,  0.00175768,
        0.11818946,  0.06209449,  0.02089658, -0.08105419,  0.15083829,
        0.22385766,  0.20492272,  0.15734573,  0.25643773,  0.18447248,
        0.10770147, -0.39407752,  0.25298354,  0.26932334,  0.25238111,
       -0.35374609, -0.35303093,  0.27756787,  0.15065001,  0.15574367,
        0.47125889,  0.45254996,  0.49301197,  0.47009373,  0.4708974 ,
        0.26474921,  0.00763435, -0.13774427,  0.08129316,  0.33924595,
        0.35963687,  0.25027198,  0.15409164,  0.15778723,  0.13179754,
        0.19229417, -0.34866897,  0.01569438, -0.36752675,  0.14631658,
        0.17868343,  0.43198636,  0.40837934,  0.01625618,  0.05426333,
        0.52490549,  0.53523601,  0.5235432 ,  0.61894984,  0.86358207,
        0.89196125,  0.74546724,  0.85922751,  0.11044163, -0.07008911,
        0.17495575,  0.35786934, -0.07424161,  0.14279865,  0.38

In [51]:
mean_squared_error(test_out, model_rf.predict(test_in))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.4s finished


0.8023511049791937

In [45]:
model_rf2 = RandomForestRegressor(n_jobs=-1, verbose=2, n_estimators=10, min_samples_split=100)
model_rf2.fit(train_in, train_out)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.


building tree 1 of 10building tree 2 of 10

building tree 3 of 10
building tree 4 of 10
building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10
building tree 9 of 10
building tree 10 of 10


[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:  1.3min finished


RandomForestRegressor(min_samples_split=100, n_estimators=10, n_jobs=-1,
                      verbose=2)

In [46]:
mean_squared_error(test_out, model_rf2.predict(test_in))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.0s finished


0.8364045063058054

In [47]:
model_rf2.predict(test_in)[:100]

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  10 out of  10 | elapsed:    0.0s finished


array([-0.04698435, -0.11613995, -0.08363304, -0.08363304, -0.1615298 ,
       -0.06835355, -0.11241288,  0.10541702,  0.21331398,  0.21331398,
        0.43805835,  0.41205835,  0.24250355,  0.01595659,  0.00967771,
        0.02212907,  0.32668526,  0.38107122,  0.22280266,  0.2829064 ,
        0.24531241, -0.63841328,  0.14334731,  0.14334731,  0.14334731,
       -0.61161202, -0.49225718,  0.01466514,  0.01466514, -0.25773069,
        0.35198198,  0.44203527,  0.44203527,  0.52203527,  0.37203527,
        0.25661038, -0.15234144, -0.186596  ,  0.01839004,  0.43728951,
        0.30307951,  0.25400753,  0.2152419 ,  0.19056707,  0.23159863,
        0.06677123, -0.62623533,  0.04800259, -0.39729266,  0.22682836,
       -0.0398383 ,  0.10573222,  0.18316812,  0.11001411, -0.1665742 ,
        0.00112163,  0.43074148,  0.43074148,  0.49770983,  0.89072165,
        0.91501832,  0.50958974,  0.94358974,  0.18181998,  0.07046783,
        0.04022798,  0.29790498, -0.28410717, -0.04250138,  0.38

In [92]:
with open('random_forest.pickle', 'wb') as f:
    pickle.dump(model_rf, f)

In [85]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [86]:
print(mean_squared_error(test_out, np.clip(model_rf.predict(test_in), -1, 1))), print(mean_squared_error(test_out, model_rf.predict(test_in)))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.8s finished


0.8005294921920726


[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.5s


0.8005294921920726


[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.7s finished


(None, None)

In [31]:
model.predict(test_in)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.3s finished


array([0.38, 0.06, 0.02, ..., 0.64, 0.68, 0.78])

In [18]:
len(train_out)

81450

In [19]:
len(test_out)

83972

In [21]:
test_out[len(test_out) - 100: len(test_out)]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
test_out[:10000]

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
with open('train.pickle', 'rb') as f:
     print(pickle.load(f))

(array([[ 3.29573577e-03, -4.13861274e-01, -4.68701032e-02, ...,
         7.70000000e+01,  0.00000000e+00,  6.00000000e+01],
       [-3.08739259e-01, -4.13861274e-01, -3.57042241e-01, ...,
         7.70000000e+01,  0.00000000e+00,  6.00000000e+01],
       [-3.08739259e-01, -8.00814069e-02, -7.70605093e-01, ...,
         7.70000000e+01,  0.00000000e+00,  6.00000000e+01],
       ...,
       [ 2.11319065e-01,  2.53698461e-01,  2.95146057e+00, ...,
         1.50000000e+01,  3.80000000e+01,  1.00000000e+02],
       [-1.66089090e+00, -9.70161054e-01,  2.95146057e+00, ...,
         1.50000000e+01,  3.80000000e+01,  1.00000000e+02],
       [-1.66089090e+00, -9.70161054e-01,  2.74467914e+00, ...,
         1.50000000e+01,  3.80000000e+01,  1.00000000e+02]]), array([0, 0, 0, ..., 0, 0, 0]))


In [43]:
import critic_model

Using TensorFlow backend.


In [62]:
critic = critic_model.make_critic_model()
    #critic.load_weights('new_critic.h5')
critic.load_weights('amazing_new_critic.h5')

In [68]:
print(mean_squared_error(test_out, critic.predict(test_in)))

0.8786159087526862


In [53]:
print(mean_absolute_error(test_out, critic.predict(test_in)))

0.7228071832494558


In [46]:
critic = critic_model.make_critic_model()
critic.load_weights('new_critic.h5')

In [47]:
print(mean_squared_error(test_out, critic.predict(test_in)))

1.0823793901960888


In [48]:
from sklearn.ensemble import HistGradientBoostingRegressor

ImportError: cannot import name 'HistGradientBoostingRegressor'

In [67]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [50]:
print(mean_absolute_error(test_out, np.clip(model.predict(test_in), -1, 1))), print(mean_absolute_error(test_out, model.predict(test_in)))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.9s finished


0.8536136935889985


[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.6s


0.8536136935889985


[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.9s finished


(None, None)

In [51]:
print(mean_absolute_error(test_out, critic.predict(test_in)))

0.7572360071721169


In [52]:
from sklearn import preprocessing

In [53]:
f = preprocessing.StandardScaler()

In [54]:
train_in_proccesed = f.fit_transform(train_in)

In [55]:
test_in_proccesed = f.transform(test_in)

In [13]:
with open('critic_scaller.pkl', 'wb') as file:
    pickle.dump(f, file)

In [21]:
import numpy as np
train_out_nine = np.zeros(train_out.shape)
for i in range(len(train_out)):
    train_out_nine[i] = 0.9 if train_out[i] == 1 else -0.9

In [23]:
train_out_nine[:100]

array([-0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9,
       -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9, -0.9,  0.9,  0.9,  0.9,
        0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,
        0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,
        0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,
        0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,
        0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,
        0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9, -0.9,
       -0.9, -0.9, -0.9, -0.9, -0.9,  0.9,  0.9,  0.9,  0.9,  0.9,  0.9,
        0.9])

In [56]:
from keras.layers import Input, Dense, Flatten, Reshape, Dropout, BatchNormalization
from keras.models import Model
from keras.callbacks import EarlyStopping
from keras.optimizers import SGD, Adam, RMSprop, Nadam
from keras import backend as K
import tensorflow as tf

In [58]:
def keras_custom_loss(y_actual, y_predicted):
    error = K.abs(y_actual - y_predicted)
    clipped_error = tf.clip_by_value(error, 0.0, 1.0)
    linear_error  = 2 * (error - clipped_error)
    return K.square(clipped_error) + linear_error


input = Input(shape=(len(test_in[0]),))
x = BatchNormalization()(input)
x = Dropout(0.2)(x)
x = Dense(256, activation='selu')(x)
x = BatchNormalization()(x)
x = Dropout(0.2)(x)
x = Dense(256, activation='selu')(x)
x = BatchNormalization()(x)
x = Dropout(0.2)(x)
output = Dense(1, activation='tanh')(x)

model = Model(input, output, name="encoder")
opt = Nadam(lr=0.00005)
model.compile(optimizer=opt, loss='mse')
model.load_weights('shok_critic.h5')

#callbacks = [EarlyStopping(monitor = 'val_loss', patience = 1)]
#model.fit(train_in_proccesed, train_out,
#                epochs=100,
#                shuffle=True,
#                batch_size=512,
#                validation_data=(test_in_proccesed, test_out), callbacks=callbacks)

In [90]:
mean_squared_error(test_out[:10000].reshape(10000, 1), ((model.predict(test_in_proccesed[:10000]) + np.array(model_rf.predict(test_in[:10000])).reshape(10000,1))/2))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished


0.7576893433259386

In [88]:
mean_squared_error(test_out[:10000].reshape(10000, 1), model.predict(test_in_proccesed[:10000]))

0.8134972117045088

In [91]:
mean_squared_error(test_out[:10000].reshape(10000, 1), np.array(model_rf.predict(test_in[:10000])).reshape(10000,1))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished


0.814512432625586

In [76]:
test_out[:100].reshape(100, 1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [77]:
((model.predict(test_in_proccesed[:100]) + model_rf.predict(test_in[:100]))/2)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished


array([[ 0.01469036, -0.06362682, -0.05905107, ...,  0.10442047,
         0.05324053,  0.21127331],
       [-0.01943529, -0.09775247, -0.09317673, ...,  0.07029481,
         0.01911488,  0.17714766],
       [ 0.12774322,  0.04942605,  0.05400179, ...,  0.21747333,
         0.16629339,  0.32432618],
       ...,
       [ 0.328733  ,  0.25041583,  0.25499157, ...,  0.41846311,
         0.36728318,  0.52531596],
       [ 0.31377385,  0.23545667,  0.24003242, ...,  0.40350396,
         0.35232402,  0.5103568 ],
       [ 0.22212993,  0.14381276,  0.1483885 , ...,  0.31186004,
         0.26068011,  0.41871289]])

In [79]:
model.predict(test_in_proccesed[:100]) + model_rf.predict(test_in[:100])

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished


array([[ 0.02938072, -0.12725363, -0.11810215, ...,  0.20884093,
         0.10648106,  0.42254663],
       [-0.03887059, -0.19550494, -0.18635346, ...,  0.14058963,
         0.03822975,  0.35429532],
       [ 0.25548644,  0.09885209,  0.10800358, ...,  0.43494666,
         0.33258679,  0.64865236],
       ...,
       [ 0.65746601,  0.50083166,  0.50998314, ...,  0.83692623,
         0.73456635,  1.05063192],
       [ 0.6275477 ,  0.47091335,  0.48006483, ...,  0.80700791,
         0.70464804,  1.02071361],
       [ 0.44425987,  0.28762552,  0.296777  , ...,  0.62372009,
         0.52136021,  0.83742578]])

In [82]:
np.array(model_rf.predict(test_in[:100])).reshape(100, 1)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished


array([[-0.00866763],
       [-0.16530198],
       [-0.1561505 ],
       [-0.1815686 ],
       [ 0.01385284],
       [ 0.0677373 ],
       [ 0.01636165],
       [ 0.20811139],
       [-0.02931016],
       [ 0.00175768],
       [ 0.11818946],
       [ 0.06209449],
       [ 0.02089658],
       [-0.08105419],
       [ 0.15083829],
       [ 0.22385766],
       [ 0.20492272],
       [ 0.15734573],
       [ 0.25643773],
       [ 0.18447248],
       [ 0.10770147],
       [-0.39407752],
       [ 0.25298354],
       [ 0.26932334],
       [ 0.25238111],
       [-0.35374609],
       [-0.35303093],
       [ 0.27756787],
       [ 0.15065001],
       [ 0.15574367],
       [ 0.47125889],
       [ 0.45254996],
       [ 0.49301197],
       [ 0.47009373],
       [ 0.4708974 ],
       [ 0.26474921],
       [ 0.00763435],
       [-0.13774427],
       [ 0.08129316],
       [ 0.33924595],
       [ 0.35963687],
       [ 0.25027198],
       [ 0.15409164],
       [ 0.15778723],
       [ 0.13179754],
       [ 0

In [28]:
print(mean_squared_error(test_out, (model.predict(test_in_proccesed) + model_rf.predict(test_in))/2))

NameError: name 'mean_squared_error' is not defined

In [112]:
rf_out = model_rf.predict(test_in)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    1.4s finished


In [114]:
ko = model.predict(test_in_proccesed)

In [117]:
summ = (ko + rf_out)/2

MemoryError: 

In [116]:
print(mean_squared_error(test_out, (ko + rf_out)/2))

MemoryError: 

In [122]:
model.save('shok_critic.h5')

In [33]:
model.predict(test_in_proccesed)[:100]

array([[-0.2703937 ],
       [-0.02546851],
       [ 0.18425106],
       [ 0.34169215],
       [ 0.5774367 ],
       [ 0.18914051],
       [ 0.30998552],
       [ 0.27702808],
       [ 0.34765086],
       [ 0.6203407 ],
       [ 0.4079286 ],
       [ 0.06844299],
       [-0.13427263],
       [ 0.09278077],
       [ 0.0464549 ],
       [-0.35477158],
       [-0.3274874 ],
       [ 0.19883531],
       [ 0.24365552],
       [ 0.1608511 ],
       [ 0.7036806 ],
       [-0.49994785],
       [-0.17553975],
       [ 0.28539866],
       [ 0.44561327],
       [ 0.49019733],
       [ 0.53138924],
       [ 0.21872433],
       [ 0.5281972 ],
       [ 0.44750586],
       [ 0.751663  ],
       [ 0.8300928 ],
       [ 0.8120593 ],
       [ 0.8527561 ],
       [ 0.9577086 ],
       [ 0.21331315],
       [-0.14622378],
       [-0.50515044],
       [-0.29527512],
       [ 0.21295051],
       [ 0.22389698],
       [ 0.43803406],
       [ 0.35066068],
       [ 0.18879871],
       [ 0.02498094],
       [-0

In [119]:
rf_out

array([ 0.06, -0.1 , -0.46, ...,  0.08,  0.  ,  0.34])